### ISSUE TITLE
Does anyone know where FSD version value is coming from on 3rd party sites?

### ISSUE THREAD

**Issue by mlancer** [teslamotors/fleet-telemetry#215]
This probably isn’t the place to ask but I’m been scratching my head with this for a while. I see 3rd party sites labeling updates with like “FSD 12.3.6”. Maybe I'm overlooking it entirely but can’t find any endpoint in the fleet api or any field from telemetry that actually provides this value. Can’t anyone point me in the direction on where this is located?

**Comment by corsair** [comment]
This information is unavailable via Fleet Telemetry or as a directly accessible value.

It can be obtained by calling the [release notes Fleet API endpoint](https://developer.tesla.com/docs/fleet-api/endpoints/vehicle-endpoints#release-notes), locating any release notes mentioning Full Self-Driving, and then extracting the FSD version from there.

Otherwise, I'm sure most services manually do this.

**Comment by mlancer** [comment]
> This information is unavailable via Fleet Telemetry or as a directly accessible value.
> 
> It can be obtained by calling the [release notes Fleet API endpoint](https://developer.tesla.com/docs/fleet-api/endpoints/vehicle-endpoints#release-notes), locating any release notes mentioning Full Self-Driving, and then extracting the FSD version from there.
> 
> Otherwise, I'm sure most services manually do this.

Thank you! I didn't have FSD until this latest demo and I'm seeing what you mean now. Thanks.
