### ISSUE TITLE
Which port is used for telemetry?

### ISSUE THREAD

**Issue by jbanyer** [teslamotors/fleet-telemetry#98]
Which network port should the telemetry service (load balancer) be listening on?

The setup [instructions](https://github.com/teslamotors/fleet-telemetry?tab=readme-ov-file#install-manually-skip-this-if-you-have-installed-with-helm-on-kubernetes) do not specify a port, and the [config](https://developer.tesla.com/docs/fleet-api#fleet_telemetry_config) endpoint does not mention supplying a port.

I realise that the server allows specifying the listening port in [server_config.json](https://github.com/teslamotors/fleet-telemetry/blob/main/examples/server_config.json), but what port do the vehicles connect to? Is it 443?

Can you include the port in `config.hostname` in the telemetry config, eg "test-telemetry.com:8443"?

**Comment by Bre77** [comment]
The setup instructions do specify a port, its literally `port` in the server config.json

As for the vehicle config, I was under the assumption `config.hostname` could include a port. For example `test-telemetry.com:8443`. If this is not the case I am will be very interested because I was somewhat depending on this.

**Comment by patrickdemers6** [comment]
Changes went out earlier this week that fix the issue of port not being used.
